// Silly and plain hbci anonymizer
const segmentNames = [
    'HNHBK',
    'HKANA',
    'HKANL',
    'HKAUB',
    'HKBAZ',
    'HKBBS',
    'HKBMB',
    'HKBME',
    'HKBML',
    'HKBSA',
    'HKBSE',
    'HKBSL',
    'HKCAZ',
    'HKCCM',
    'HKCCS',
    'HKCDB',
    'HKCDE',
    'HKCDL',
    'HKCDN',
    'HKCDU',
    'HKCMB',
    'HKCME',
    'HKCML',
    'HKCMU',
    'HKCSA',
    'HKCSB',
    'HKCSE',
    'HKCSL',
    'HKCSU',
    'HKCUB',
    'HKCUM',
    'HKDAB',
    'HKDAE',
    'HKDBS',
    'HKDDB',
    'HKDDE',
    'HKDDL',
    'HKDDN',
    'HKDDU',
    'HKDMB',
    'HKDMC',
    'HKDME',
    'HKDML',
    'HKDSA',
    'HKDSB',
    'HKDSC',
    'HKDSE',
    'HKDSL',
    'HKDSW',
    'HKEKA',
    'HKEND',
    'HKFGA',
    'HKFGB',
    'HKFGK',
    'HKFGN',
    'HKFRD',
    'HKIDN',
    'HKINF',
    'HKISA',
    'HKKAN',
    'HKKAU',
    'HKKAZ',
    'HKKIA',
    'HKPAE',
    'HKPPD',
    'HKPRO',
    'HKPSP',
    'HKQTG',
    'HKSAK',
    'HKSAL',
    'HKSPA',
    'HKSSP',
    'HKSYN',
    'HKTAB',
    'HKTAN',
    'HKTAU',
    'HKTAZ',
    'HKTST',
    'HKTSY',
    'HKTUB',
    'HKTUE',
    'HKUEB',
    'HKVVB',
    'HKWPD',
    'HKZDF',
    'DKKKU',
    'DKPAE',
    'DKURK',
    'HIANA',
    'HIANL',
    'HIAUB',
    'HIAZS',
    'HIBAZ',
    'HIBBS',
    'HIBMB',
    'HIBME',
    'HIBML',
    'HIBPA',
    'HIBSA',
    'HIBSE',
    'HIBSL',
    'HICAZ',
    'HICCM',
    'HICCS',
    'HICDB',
    'HICDE',
    'HICDL',
    'HICDN',
    'HICDU',
    'HICMB',
    'HICME',
    'HICML',
    'HICMU',
    'HICSA',
    'HICSB',
    'HICSE',
    'HICSL',
    'HICSU',
    'HICUB',
    'HICUM',
    'HIDAB',
    'HIDAE',
    'HIDAL',
    'HIDAN',
    'HIDBS',
    'HIDDB',
    'HIDDE',
    'HIDDL',
    'HIDDN',
    'HIDDU',
    'HIDMB',
    'HIDMC',
    'HIDME',
    'HIDML',
    'HIDSA',
    'HIDSB',
    'HIDSC',
    'HIDSE',
    'HIDSL',
    'HIDSW',
    'HIEKA',
    'HIFGA',
    'HIFGB',
    'HIFGK',
    'HIFGN',
    'HIFRD',
    'HIINF',
    'HIJKL',
    'HIKAN',
    'HIKAU',
    'HIKAZ',
    'HIKIA',
    'HIKIM',
    'HIKOM',
    'HIKPV',
    'HILAS',
    'HIPAE',
    'HIPIN',
    'HIPPD',
    'HIPRO',
    'HIPSP',
    'HIQTG',
    'HIRMG',
    'HIRMS',
    'HIRMX',
    'HISAL',
    'HISHV',
    'HISPA',
    'HISYN',
    'HITAB',
    'HITAN',
    'HITAU',
    'HITAZ',
    'HITSY',
    'HITUA',
    'HITUB',
    'HITUE',
    'HITUL',
    'HIUEB',
    'HIUMB',
    'HIUPA',
    'HIUPD',
    'HIVIS',
    'HIWPD',
    'HIxxx',
    'HIZDF',
    ]
    const reservedMessages = {
        mt940: "---- SWIFT MT-940 ----",
        remittSent: "---- Gesendete SEPA remitt ----",
        remittRecieved: "---- Empfangen SEPA remitt ----",
        debitSent: "---- Gesendete SEPA debit ----",
        debitRecieved: "---- Empfangen SEPA debit ----",
        messageSent: "---- Gesendete HBCI Nachricht ----",
        messageRecieved: "---- Empfangene HBCI Nachricht ----",
        messageError: "---- Fehler beim Empfang der HBCI Nachricht ----",
        dialogSynchronization: "---- Synchronisierung HBCI Dialog ----",
        dialogInitialization: "---- Initialisierung HBCI Dialog  ----",
        dialogNeedTAN: "---- Brauchen TAN ----",
        dialogChallenging: "---- Herausfordern ----",
        dialogSelectTANMedia: "---- Wählen TAN Media ----",
        dialogError: "---- Dialog Fehler ----",
        dialogEnd: "---- Beendet HBCI Dialog ----",
    }
    
    const reservedMessagesArr = Object.values(reservedMessages);
    
    const allReserved = segmentNames.concat(reservedMessagesArr);

    module.exports = allReserved;